version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .         # pasta onde está o Dockerfile
      dockerfile: Dockerfile
    container_name: minha-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meu_banco
      SPRING_DATASOURCE_USERNAME: meu_usuario
      SPRING_DATASOURCE_PASSWORD: minha_senha

volumes:
  postgres_data:
